### ISSUE TITLE
education profile tidak bisa di submit kalau belum diisi semua

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/ats-core#104]
![image](https://user-images.githubusercontent.com/2850146/42917402-9337f5c8-8b33-11e8-8a92-426f298ed4d2.png)

hanya education level & organization yg harus diisi.
!!! label input yg organization masih salah. masih tertulis education level

**Comment by YudhaWork033** [comment]
Mas @renowijoyo 

Mohon dikoreksi kembali.

![image](https://user-images.githubusercontent.com/38399980/42929603-c1ebe042-8b64-11e8-9092-cf9e10fbc5e5.png)

![image](https://user-images.githubusercontent.com/38399980/42929647-e0eaee2a-8b64-11e8-85a3-ac93cea5205f.png)
