### ISSUE TITLE
contacts CRUD

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/ats-core#12]

**Comment by afrastgeek** [comment]
belum bisa menambahkan kontak

**Comment by YudhaWork033** [comment]
@afrastgeek 

mas, di table profile harus ada dlu valuenya mas. :)

![image](https://user-images.githubusercontent.com/38399980/41077642-15864330-6a42-11e8-88af-901a230aad6b.png)

![image](https://user-images.githubusercontent.com/38399980/41077672-42391e20-6a42-11e8-9e0d-0b69ebbd31f0.png)

**Comment by afrastgeek** [comment]
ya, saya sudah buat profile untuk akun tersebut terlebih dahulu. tapi tetap "Failed Insert Data".

Saran saya, selain dibenahi logic di method controllernya, tidak perlu menggunakan try catch juga. karena validator sudah langsung melakukan redirect dan menampilkan pesan error

**Comment by YudhaWork033** [comment]
Mohon retest ya

Sample 

DB profile
![image](https://user-images.githubusercontent.com/38399980/41145130-47a3f1c2-6b29-11e8-9ddf-f3912dc0e61e.png)

DB user
![image](https://user-images.githubusercontent.com/38399980/41145153-5c9d4ef2-6b29-11e8-897e-89e77b1fc8b7.png)

Hasil 
![image](https://user-images.githubusercontent.com/38399980/41145085-245e7ff2-6b29-11e8-8ea3-925c0a8b2283.png)

Delete
![image](https://user-images.githubusercontent.com/38399980/41145212-91085786-6b29-11e8-9203-ed6a0cfb462d.png)

Update
![image](https://user-images.githubusercontent.com/38399980/41145240-ad4c8cfa-6b29-11e8-8e34-5174cdba7899.png)

Thanks
