### ISSUE TITLE
notification/alert system buat di web app

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/ats-core#35]
- [x] sistem notification harus fleksibel dan tercatat di database.
- [x] propose design table/migration untuk mendukung fungsi ini

**Comment by YudhaWork033** [comment]
Team,

Berikut ya test nya ,

1. API 

**Broadcast**

http://localhost:8000/pushall
Accept:application/json 
x-csrf-token:tNNErOJTbJ25IP8SpmwHRIlWGaHTow11QQMUdrx4

**Payload** 
{

	"title" :"Send",
	"body" : "Test Broadcast Notification"
}

![image](https://user-images.githubusercontent.com/38399980/41774097-7f64d96c-7648-11e8-9b3a-ff5229bec3ce.png)

curl -i -H Accept:application/json -H x-csrf-token:tNNErOJTbJ25IP8SpmwHRIlWGaHTow11QQMUdrx4 -X POST http://localhost:8000/push -H Content-Type: application/json -d ' { "to" : "2", "title" :"TEST BOD'Y", "body" : "TEST BODY" } '

![image](https://user-images.githubusercontent.com/38399980/41773903-de107526-7647-11e8-8f08-6549fd027d08.png)

Ketika di hit secara real time akan muncul notif 

![image](https://user-images.githubusercontent.com/38399980/41774026-39ddae0a-7648-11e8-871b-a55ca0188c56.png)



**Personal**

http://localhost:8000/push
Accept:application/json 
x-csrf-token:tNNErOJTbJ25IP8SpmwHRIlWGaHTow11QQMUdrx4

**Payload** 
{
	"to" : "2",
	"title" :"TEST Person",
	"body" : "TEST BODY"
}

![image](https://user-images.githubusercontent.com/38399980/41774183-d081c1a2-7648-11e8-9e4c-a40d09f423d1.png)

**DB**
![image](https://user-images.githubusercontent.com/38399980/41774219-e9306488-7648-11e8-8751-bc637ecf1e73.png)

![image](https://user-images.githubusercontent.com/38399980/41774320-614d9d64-7649-11e8-920d-33460b667a32.png)

di pusher 
![image](https://user-images.githubusercontent.com/38399980/41774365-a47a3642-7649-11e8-8482-39f94b11c3cc.png)

depedecies
pusher.com
npm install or  npm install --save laravel-echo pusher-js

Note:
Mark dan Unmark (on progress)

**Comment by YudhaWork033** [comment]
team,

Branch (p2-ats-core)

**Comment by YudhaWork033** [comment]
env

PUSHER_APP_ID=xxxx
PUSHER_APP_KEY=xxxx
PUSHER_APP_SECRET=xxxx
PUSHER_APP_CLUSTER=xxxx

**Comment by afrastgeek** [comment]
@YudhaWork033 lebih baik langsung dibuat pull requestnya saja.

detail teknis seperti https://github.com/gamantha/ats-core/issues/35#issuecomment-399411428 ini juga sebaiknya di simpan pull request.

**Comment by YudhaWork033** [comment]
O iya yak, ok mas
