### ISSUE TITLE
Event Management (CRUD)

### ISSUE THREAD

**Issue by afrastgeek** [gamantha/ats-core#54]
Event merupakan seluruh acara dari sebuah organisasi.

Tipenya bisa beragam, misal `recruitment` atau `assessment`.
Misalnya:
- Suatu organisasi akan mengadakan kegiatan rekrutment, maka dibuat event dengan `event_type` `recruitment`.
- Suatu organisasi akan mengadakan kegiatan assessment psikologi, maka dibuat event dengan `event_type` `assessment`
    jadi acaranya judulny assessment, dimana didalamnya akan banyak individual assessment

---

Event management ini **bukan** https://laravel.com/docs/5.6/events

**Comment by renowijoyo** [comment]
'create new event 'http://ats.dev.ppsdm.com/admin/events masih belum jalan

**Comment by afrastgeek** [comment]
belum jalan karena halaman `/admin/events` menggunakan view milik `/events` yang mengarah ke route `events`. sedangkan route `events` diberi middleware hanya untuk `org:admin`.

Will be solved on https://github.com/gamantha/ats-core/pull/79
