### ISSUE TITLE
Employee Registration

### ISSUE THREAD

**Issue by afrastgeek** [gamantha/ats-core#56]
employee adalah profile yang mempunyai data di tabel work yang menghubungkan profileId dengan organizatonId

user/profile yang menjadi employee BELUM TENTU mempunya akses ke controller organization. jadi tidak punya row di organizational_roles. (penambahan roles ini dilakukan oleh org:admin)

employee registration meliputi semua kemungkinan untuk mengisi data di tabel WORK
1. user mengisi data work dia untuk bekerja di organisasi A. dia harus search organisasinya. tidak bisa add sendiri (ada satu pilihan organisasi yang 'not listed yet'). data work statusnya defaultnya ke 'unverified'. ini harus di verify oleh org:admin yg bersangkutan
2. org:admin mengisi data work sebuah profile (seperti no.1 tapi diisikan oleh admin karena tidak punya user. dan hanya status work untuk oganisasi itu saja). work status 'verified'
3. apabila belum ada user maupun profile maka tidak bisa didaftarkan dia sebagai employee.

**Comment by renowijoyo** [comment]
@putrastti @YudhaWork033 harus ada update di tabel work di tambahkan dengan field status (varchar 255)
