### ISSUE TITLE
Organization Role Management (Crud Role Organisasi)

### ISSUE THREAD

**Issue by afrastgeek** [gamantha/ats-core#58]
User dengan role `system:admin` dapat menambahkan user sebagai role `org:admin` dan role lainnya ke suatu organisasi.

---

~~Harus menunggu https://github.com/gamantha/ats-admin/issues/15 selesai.~~

---

- [ ] Buat controller untuk Role CRUD di namespace `App\Http\Controllers\Admin\`.

- [ ] Buat view untuk crud di folder `resources\views\admin\`.

**Comment by afrastgeek** [comment]
@Pholenk karena https://github.com/gamantha/ats-admin/issues/15 sudah selesai, mohon untuk membuat controller dan view di folder admin.

**Comment by YudhaWork033** [comment]
Done. Mohon dibantu recheck.

![image](https://user-images.githubusercontent.com/38399980/40645708-5c37a79e-6351-11e8-8931-d3a7c542e6c6.png)

![image](https://user-images.githubusercontent.com/38399980/40645729-6d984584-6351-11e8-9e2f-f176bc4c4c17.png)

nambah middleware 
![image](https://user-images.githubusercontent.com/38399980/40645753-7bbbb36c-6351-11e8-9d3a-353afd5045ae.png)

hasilnya admin dapat access crud organization 
![image](https://user-images.githubusercontent.com/38399980/40645801-9aea66ac-6351-11e8-9ebe-efb22d64eab6.png)

sedangkan recruiter hanya bisa view
![image](https://user-images.githubusercontent.com/38399980/40645868-c69f4826-6351-11e8-8702-1e8889186022.png)

jika diklik tombol edit 
![image](https://user-images.githubusercontent.com/38399980/40645895-de51f2e8-6351-11e8-8895-d55ed266abeb.png)

Thanks
