### ISSUE TITLE
no role_name field di organizational_role

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/ats-core#80]
![image](https://user-images.githubusercontent.com/2850146/40895250-7d90f48c-67d8-11e8-91e5-39df4f36783e.png)

---

(edit afr):
Selain itu, migration untuk tabel `organizational_role` juga masih berisi kolom yang sama persis dengan tabel `organizations`. Seharusnya seperti gambar berikut:

![image](https://user-images.githubusercontent.com/4904057/40899486-6a3e8110-67f1-11e8-9aba-ab2149a8179c.png)

**Comment by YudhaWork033** [comment]
bukannya ini ya mas 
(organization_roles)
![image](https://user-images.githubusercontent.com/38399980/40900097-2d949148-67f4-11e8-955e-6ee7d8a1c901.png)

(organizational)
![image](https://user-images.githubusercontent.com/38399980/40900142-5e72e012-67f4-11e8-9660-78eb4a17b60b.png)

**Comment by YudhaWork033** [comment]
@renowijoyo 

![image](https://user-images.githubusercontent.com/38399980/40904721-ce67c5b6-6805-11e8-91b0-d5b8eebabe15.png)

mohon dibantu reviewnya kembali

**Comment by YudhaWork033** [comment]
ini sepertinya butuh di refresh aja mas 

code di dev

![image](https://user-images.githubusercontent.com/38399980/40905040-ddac7160-6806-11e8-8a9f-72cbc9e2e943.png)

**Comment by afrastgeek** [comment]
@YudhaWork033 terima kasih atas respon dan review nya.

kendala yang dimaksud di issue ini sebetulnya terjadi di development server.
terkait https://gamantha.slack.com/archives/GA6M9NT5E/p1528098899000409

untuk masalah ini sudah saya solve.
